/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package format;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author eon
 */
public class JFrameFont extends javax.swing.JFrame {

    private JTextArea jtextArea;
    private String[] fontNames;

    String fonts[];
    String sizeFonts[];
    //Font fontAll[];
    /**
     * Creates new form JFrameFont
     */
    public JFrameFont() {
        initComponents();
        loadFonts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelFont = new javax.swing.JPanel();
        jTextFieldFontSelect = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFont = new javax.swing.JList<>();
        jPanelSizeFont = new javax.swing.JPanel();
        jTextFieldSizeFont = new javax.swing.JTextField();
        jScrollPaneSizeFont = new javax.swing.JScrollPane();
        jListSizeFont = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSample = new javax.swing.JLabel();

        setTitle("Font");
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelFont.setBorder(javax.swing.BorderFactory.createTitledBorder("Font"));
        jPanelFont.setLayout(new java.awt.BorderLayout());

        jTextFieldFontSelect.setText(this.jListFont.getSelectedValue());
        jTextFieldFontSelect.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanelFont.add(jTextFieldFontSelect, java.awt.BorderLayout.NORTH);

        jListFont.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListFontMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListFont);

        jPanelFont.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelFont, java.awt.BorderLayout.CENTER);

        jPanelSizeFont.setBorder(javax.swing.BorderFactory.createTitledBorder("Size"));
        jPanelSizeFont.setLayout(new java.awt.BorderLayout());

        jTextFieldSizeFont.setText("12");
        jTextFieldSizeFont.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanelSizeFont.add(jTextFieldSizeFont, java.awt.BorderLayout.NORTH);

        jListSizeFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSizeFontMouseClicked(evt);
            }
        });
        jScrollPaneSizeFont.setViewportView(jListSizeFont);

        jPanelSizeFont.add(jScrollPaneSizeFont, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelSizeFont, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancel.setText("Cancel");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 100, -1));

        jButtonAccept.setText("Accept");
        jButtonAccept.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, -1));

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sample"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSample.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelSample.setText("JNotepad ");
        jLabelSample.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel2.add(jLabelSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 270, 80));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        this.jtextArea.setFont(new Font(this.jTextFieldFontSelect.getText(),Font.PLAIN,Integer.parseInt(this.jTextFieldSizeFont.getText())));
        
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jListFontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListFontMouseClicked
        this.jTextFieldFontSelect.setText(this.jListFont.getSelectedValue());
        this.jLabelSample.setFont(new Font(this.jTextFieldFontSelect.getText(),Font.PLAIN,40));
    }//GEN-LAST:event_jListFontMouseClicked

    private void jListSizeFontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSizeFontMouseClicked
        this.jTextFieldSizeFont.setText(this.jListSizeFont.getSelectedValue());
    }//GEN-LAST:event_jListSizeFontMouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public void setTextArea(JTextArea jtextAreaValue)
    {
        this.jtextArea = jtextAreaValue;
    }
    public void loadFonts(){

        GraphicsEnvironment ge = GraphicsEnvironment
        .getLocalGraphicsEnvironment();
        
        //this.fontAll = ge.getAllFonts();
        this.jListFont.setListData(ge.getAvailableFontFamilyNames());
        
        this.sizeFonts = new String[22];
        for(int s = 0 ; s < this.sizeFonts.length; s++){
            this.sizeFonts[s] = Integer.toString(s);
        }
        this.jListSizeFont.setListData(this.sizeFonts);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelSample;
    private javax.swing.JList<String> jListFont;
    private javax.swing.JList<String> jListSizeFont;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFont;
    private javax.swing.JPanel jPanelSizeFont;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneSizeFont;
    private javax.swing.JTextField jTextFieldFontSelect;
    private javax.swing.JTextField jTextFieldSizeFont;
    // End of variables declaration//GEN-END:variables
}
